// react/src/components/Result/index.js
import React from "react";

import "./style.css";
import { ResultColor } from "../ResultColor";

export const Result = props => (
  <div className="guess-row-result">
    <div className="guess-row-result-row">
      {props.result
        .slice(0, (props.result.length + 1) / 2)
        .map((result, index) => (
          <ResultColor key={index} color={result} />
        ))}
    </div>
    <div className="guess-row-result-row">
      {props.result
        .slice((props.result.length + 1) / 2)
        .map((result, index) => (
          <ResultColor key={index} color={result} />
        ))}
    </div>
  </div>
);

// svelte/src/components/Result.svelte
<script>
  import ResultColor from "./ResultColor.svelte";

  export let result;
  export let hideResults = false;
</script>

<style>
  .guess-row-result {
    padding: 8px;
    display: flex;
    flex-direction: column;
  }

  .guess-row-result-row {
    display: flex;
  }

  .placeholder {
    width: 20px;
  }
</style>

<div class="guess-row-result">
  <div class="guess-row-result-row">
    {#each result.slice(0, (result.length + 1) / 2) as result}
      {#if hideResults}
        <div class="placeholder" />
      {:else}
        <ResultColor color={result} />
      {/if}
    {/each}
  </div>
  <div class="guess-row-result-row">
    {#each result.slice((result.length + 1) / 2) as result}
      {#if hideResults}
        <div class="placeholder" />
      {:else}
        <ResultColor color={result} />
      {/if}
    {/each}
  </div>
</div>
